# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wishart <- function(df, S) {
    .Call('_BMTME_wishart', PACKAGE = 'BMTME', df, S)
}

inv_wishart <- function(df, S) {
    .Call('_BMTME_inv_wishart', PACKAGE = 'BMTME', df, S)
}

MVnormvv <- function(mean, S) {
    .Call('_BMTME_MVnormvv', PACKAGE = 'BMTME', mean, S)
}

MatMul <- function(X, Y) {
    .Call('_BMTME_MatMul', PACKAGE = 'BMTME', X, Y)
}

Krone <- function(A, B) {
    .Call('_BMTME_Krone', PACKAGE = 'BMTME', A, B)
}

# Register entry points for exported C++ functions
methods::setLoadAction(function(ns) {
    .Call('_BMTME_RcppExport_registerCCallable', PACKAGE = 'BMTME')
})
