# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wishart <- function(df, S) {
    .Call(`_BMTME_wishart`, df, S)
}

inv_wishart <- function(df, S) {
    .Call(`_BMTME_inv_wishart`, df, S)
}

MVnorm <- function(n, mean, S) {
    .Call(`_BMTME_MVnorm`, n, mean, S)
}

MVnormvv <- function(mean, S) {
    .Call(`_BMTME_MVnormvv`, mean, S)
}

MatMul <- function(X, Y) {
    .Call(`_BMTME_MatMul`, X, Y)
}

Krone <- function(A, B) {
    .Call(`_BMTME_Krone`, A, B)
}

